Repository Thisiseanxu/gacha-party, pull requests merged in 2025-07, with the labels that each got.

#16 Feat/抽卡分析添加分池和历史记录显示时间
  src/components/SelectorComponent.vue
  src/components/SwitchComponent.vue
  src/styles/colors.js
  src/views/RecordPage.vue
Labels: 功能

#15 Feat/小助手主页
  package-lock.json
  public/fonts/Inter.otf
  src/main.js
  src/resources/fonts/youshebiaotihei.ttf
  src/views/GachaHomePage.vue
  src/views/HomePage.vue
  vite.config.js
Labels: 功能, 需要帮助

#20 Feat/抽卡记录软件更新
  package-lock.json
  package.json
  public/data/database_6.json
  public/data/version.json
  src/data/cardPools.js
  src/views/RecordPage.vue
Labels: 功能

#27 Feat/自定义卡池
  src/data/cardPools.js
  src/main.js
  src/utils/useGacha.js
  src/views/CustomGachaPage.vue
  src/views/GachaHomePage.vue
  src/views/GachaPage.vue
  src/views/RecordPage.vue
Labels: 功能, 已完成
